### ISSUE TITLE
No Airline ID in Request modal

### ISSUE THREAD

**Issue by pokertour** [DarkArtek/vamsys-discord-access-bot#13]
Hello Luca,
i got your app working, but when i click on the button request access the airline id in not display in Pilot ID field, there is a screenshot.
![image](https://github.com/DarkArtek/vamsys-discord-access-bot/assets/7757451/0ef77b4c-0dcc-407c-97c3-b34d79abe8c8)

I don't know if i need to do something on my side or not ?

Thank's

**Comment by DarkArtek** [comment]
Seems that is not reading the airlineID.

Send via email to me your config and i'll check.

**Comment by pokertour** [comment]
Seems fixed in my PR with nickname setting, strange

**Comment by DarkArtek** [comment]
Ok, then ill approve your PR
